### ISSUE TITLE
First pass of feedback suggestions

### ISSUE THREAD

**Issue by roryspanton** [benwhalley/lifesavR#19]
These are issues from my first pass of the newly updated materials. I've already fixed a few minor typos. I've marked the most critical issues I found in bold so that they can be prioritised.

## Main Index Page

- [x] Chris Berry should be listed as a co-author on the site heading given that he contributed to worksheet 6.
- [x] Under the heading "Access to R", the sentence “Staff won’t help you debug your work unless they are evident when using the school RStudio server” could be revised for clarity.
- [x] Items under heading XXX TODO ADD ITEMS FOR should ideally be added before term starts.
- [x] Links "Prior preparation" and "Causal Models XXX" do not redirect and look to be incomplete.

## 1. Getting Started

- [x] Video for using the R interface is out of date – The URL for our RStudio online portal has changed, and our RStudio login now uses SAML. Sonja’s instructions about the URL and checking emails for a password sent by the tech office team may therefore be confusing.
- [x] The “before you start” video ends abruptly before the function has finished executing. Likewise the next “using the workbooks” video starts with the function having completed and Sonja in mid-sentence. This may be confusing to students.
- [x] Exercise 5: inconsistency in the worksheet vs the rmarkdown file; rmarkdown file says “show first 10 rows…”, worksheet says first 6. First 6 is the default output given by `head()` and so is correct, as far as I can tell.

## 2. Working with R

- [x] Sonja’s video on pipes refers to the mtcars dataset being used previously, which isn’t the case in the updated materials. She also works with the mtcars dataset in the video, whereas the fuel dataset is used instead in the materials. Not sure if this needs correcting, but thought I’d highlight the inconsistency.
- [x] “Loading data from elsewhere” video and code examples tab uses the “shootings” dataset, whereas the updated worksheet uses the world happiness survey. The video transcription tab also mentions a “food.csv” dataset that doesn’t appear anywhere else. I suggest these inconsistencies should be amended to be consistent with the use of the happiness data, as in the rmarkdown files.
- [x] The method of downloading a csv from a webpage is different on Windows ([see link](https://support.google.com/chrome/answer/7343019?hl=en-GB&co=GENIE.Platform%3DDesktop)) from the method described in the video. This should be made explicit to students to avoid confusion.
- [x] **Additional resources video on saving to a csv is not present (comes up as a black iframe)**
- [x] Exercise 8: median weight answer should be 1508kg, but this is coming up as wrong when I input it in the webpage. Not sure what’s going on here – the correct answer median calculation in the website rmd file is also 1508.
- [x] In Exercise 10 of the worksheet, the greater than symbol is escaped as a character, rather than expressed in words. Students may not know what the “\\>” symbol combination means, so it’s probably best to use “greater than” in this case like in the previous exercises.

## 4. Describing Patterns, Answering Questions

- [x] This more a suggestion than an issue per se, but it might be worth separating code and output in the “code examples” tab more explicitly (e.g. in the frequency of responses section). I’ve seen students get confused and try to run output as code from worksheets before.
- [x] Relationships, video summary tab. Suggest changing wording of description of strength of evidence for Bayes Factor. Currently says “>3 is considered good” but I’d recommend a different adjective (the BF indicates strength, not “goodness”).

## 5. Quantifying Evidence

- [x] Consider defining “replicate” in video summary tab of “is this pattern a fluke”. While the concept is mentioned in the video, the term is not explicitly defined anywhere. This might be helpful to any students who aren’t clear on the term’s meaning in this instance.
- [x] Similarly, mention that BayesFactor is a package in the video summary tab for Bayesian t-test for maximum clarity.
- [x] In Exercise 1, “calculate each group’s weight” is a little vague. Is it worth explicitly requesting students to calculate a mean here?
- [x] **In Exercise 1, the markdown exercise document prompts students to use `with()` alongside `ttestBF()` to calculate their Bayes Factor.** The `with()` function is only introduced in the next video, and doesn’t seem to work with a ttestBF formula anyway.
- [x] Could be worth having a “check answer” box for the final BF calculation in Exercise 1 to give students reassurance that they’re doing it right.

## 6. Making Predictions

- [x] Navigation links should be added to the Topics Covered index at the top of the page, as with the other worksheets.
- [x] **None of the videos in this worksheet are visible – there are just blank spaces where they should be. Tested in two browsers (Chrome and Edge). Should be fixed as a priority.**
- [x] In Example 3 of further reading exercises, the “True” option is missing from the “The relationship looks linear” dropdown menu.

## 7. Building Models

- [x] **Same issue with videos not displaying as in previous worksheet.**
- [x] **Transcript for first video not available either.**
- [x] In the transcript for the strength of evidence video, the last code chunk has a comment stating “evidence in favour of model A”, whereas the explanation of the output below states that the same BF is evidence in favour of model B.
- [x] Note: consider that students may be confused by the introduction of different Bayes Factor interpretation guidelines in this worksheet after they just learned a different set of simpler heuristics in the previous worksheet. Consider using one consistent set of reporting guidelines.
- [x] In extension Task 5, there is no assigned correct answer for the “The Bayes Factor for model B is:” dropdown question. Should be “much more than 6”.

## 8. Reporting Results

- [x] **The links to the regression-reporting-example documents (both pdf and word) redirect to a 404 page.**
- [x] **The check answers section of the task under heading “The formula” is blank.**
- [x] **Check your knowledge section is currently incomplete.**

**Comment by benwhalley** [comment]
Hi Rory - just working through.  Thanks for being so thorough.


2. Working with R

>In Exercise 10 of the worksheet, the greater than symbol is escaped as a character, rather than expressed in words. >Students may not know what the “>” symbol combination means, so it’s probably best to use “greater than” in this case >like in the previous exercises.

I can't replicate this Rory - can you show me what you mean?



On this: 
`This more a suggestion than an issue per se, but it might be worth separating code and output in the “code examples” tab more explicitly (e.g. in the frequency of responses section). I’ve seen students get confused and try to run output as code from worksheets before.`

I think this is a really good idea but don't know how to implement it. Did you have something in mind?

**Comment by roryspanton** [comment]
No worries! The first point refers to the use of "\\>" in the session 2 RMarkdown workbook:

![image](https://user-images.githubusercontent.com/51744937/190651303-d5e2a667-4702-4a83-84ee-e30409ab912a.png)

I was concerned students would be confused by the backslash in this context, so I suggest changing this to "mean miles per gallon of cars with engine size greater than 3000".

On the input/output separation comment, here are some ideas:
- Reserving grey code boxes for executable code, and using another colour for output
- Commenting output (example below) to make it clear that it's not executable, and prevent it from running if students copy it to their R consoles anyway

```# numbers of men and women
earnings %>%
  count(gender)

# Output:
#  gender    n
# 1 female 2130
# 2   male 2353

**Comment by benwhalley** [comment]
Hi Rory - I have fixed all of these issues (thanks) and pushed updates to the live site. I think many of the issues you spotted were actually because I hadn't previously updated the version you were looking at. Either way though, now would be a great time to check the first 2 sessions again if possible. We can chat on Monday about sessions 6-8.

**Comment by roryspanton** [comment]
All sounds great! Thanks for addressing all of these points so quickly. I'll take another look at the first two sessions and file any remaining issues separately.
